import express from "express";
import cors from "cors";
import mongoose from "mongoose";
import authRoutes,{requireAuth} from "./routes/auth.js";
import customersRoutes from "./routes/customers.js";
const app=express();
app.use(cors());
app.use(express.json());
mongoose.set("strictQuery",true);
mongoose.connect(process.env.MONGODB_URI).then(()=>console.log("mongo connected")).catch(e=>console.error(e));
app.get("/api/health",(req,res)=>res.json({ok:true}));
app.use("/api/auth",authRoutes);
app.use("/api/customers",requireAuth,customersRoutes);
const PORT=process.env.PORT||3000;
app.listen(PORT,()=>console.log("listening",PORT));
export default app;
